version: "1.0.1"
services:
  client:
    image: client-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: dev-client
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  server:
    image: server-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: dev-server
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
