version: "1.0.1"
services:
  client:
    image: client-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: dev-client
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_SERVER_HOST=http://localhost/8000

  server:
    image: server-dev-i
    build:
      dockerfile: Dockerfile.dev
    container_name: dev-server
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - JWT_KEY="enter_your_random_key_here"
      - DATABASE_URL="postgresql://database:randompassword@localhost:5432/test"

  database:
    image: postgresql
    container_name: petconnect
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./database_data:/var/lib/postgresql/data

volumes:
  node_modules:
