version: "1.0.1"

services:
  client:
    build:
      context: ./client

  server:
    build:
      context: ./server

  database:
    image: postgresql:latest
    container_name: petconnect
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./database_data:/var/lib/postgresql/data
