version: "1.0.1"
services:
  client:
    image: client-prod-i
    build:
      dockerfile: Dockerfile.prod
    container_name: prod-client
    ports:
      - "4000:80"
    environment:
      - NODE_ENV=production

  server:
    image: server-prod-i
    build:
      dockerfile: Dockerfile.prod
    container_name: prod-server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
